version: 2
updates:
  # Python package dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "brightlikethelight"
    reviewers:
      - "brightlikethelight"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # GitHub Actions dependencies  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "brightlikethelight"
    reviewers:
      - "brightlikethelight"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/deploy/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "brightlikethelight"
    reviewers:
      - "brightlikethelight"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"