version: '3.8'

services:
  music21-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # MCP servers use stdio transport - no ports needed
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=WARNING
      - REDIS_URL=redis://redis:6379/0
      - MCP_PRODUCTION=true
      # Resource limits for production
      - MEMORY_LIMIT_MB=512
      - MAX_SCORES=100
    depends_on:
      redis:
        condition: service_healthy
    # Health check with shorter intervals for production
    healthcheck:
      test: ["CMD", "python", "/app/src/music21_mcp/health_check.py"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    volumes:
      - music21_data:/app/data
      - music21_logs:/app/logs
      # Read-only access to source for security
      - ./src:/app/src:ro
    networks:
      - music21_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --save 60 1000
    ports:
      - "127.0.0.1:6379:6379"  # Bind to localhost only for security
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.2'
    networks:
      - music21_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Production monitoring and alerting
  mcp-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - ALERT_MEMORY_THRESHOLD=80
      - ALERT_DISK_THRESHOLD=85
    depends_on:
      - music21-mcp
      - redis
    command: ["python", "-c", "
import time, psutil, logging;
logging.basicConfig(level=logging.INFO);
logger = logging.getLogger('monitor');
[
  logger.warning(f'ALERT: Memory usage {mem}%') if (mem := psutil.virtual_memory().percent) > 80 
  else logger.info(f'Memory: {mem}%, Disk: {psutil.disk_usage(\"/\").percent}%') 
  or time.sleep(30) 
  for _ in iter(int, 1)
]"]
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    volumes:
      - music21_logs:/app/logs
    networks:
      - music21_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  music21_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  music21_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  redis_data:
    driver: local

networks:
  music21_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16