apiVersion: v2
name: music21-mcp
description: Music21 MCP Server with OAuth2 authentication for secure remote access
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Bright-L01/music21-mcp-server
sources:
- https://github.com/Bright-L01/music21-mcp-server
maintainers:
- name: music21-mcp-team
  email: maintainer@example.com
keywords:
- music
- analysis
- mcp
- oauth2
- api
- music21
annotations:
  category: Development
  licenses: MIT
dependencies:
- name: redis
  version: "17.15.2"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
- name: nginx
  version: "15.4.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: nginx.enabled
- name: cert-manager
  version: "v1.13.2"
  repository: "https://charts.jetstack.io"
  condition: certManager.enabled