apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "music21-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "music21-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "music21-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "music21-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "music21-mcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        env:
        # Basic configuration
        - name: HOST
          value: {{ .Values.config.host | quote }}
        - name: PORT
          value: {{ .Values.config.port | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        - name: PYTHONUNBUFFERED
          value: "1"
        
        # Redis configuration
        {{- if .Values.redis.enabled }}
        - name: REDIS_URL
          value: "redis://{{ include "music21-mcp.redis.fullname" . }}-master:6379/0"
        {{- if .Values.redis.auth.enabled }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "music21-mcp.redis.secretName" . }}
              key: {{ include "music21-mcp.redis.secretPasswordKey" . }}
        {{- end }}
        {{- end }}
        
        # OAuth2 configuration
        - name: OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES
          value: {{ .Values.config.oauth2.accessTokenExpireMinutes | quote }}
        - name: OAUTH2_REFRESH_TOKEN_EXPIRE_DAYS
          value: {{ .Values.config.oauth2.refreshTokenExpireDays | quote }}
        - name: OAUTH2_REQUIRE_PKCE
          value: {{ .Values.config.oauth2.requirePkce | quote }}
        
        # Session configuration
        - name: SESSION_TTL_MINUTES
          value: {{ .Values.config.session.ttlMinutes | quote }}
        - name: SESSION_MAX_PER_USER
          value: {{ .Values.config.session.maxPerUser | quote }}
        
        # CORS configuration
        - name: CORS_ORIGINS
          value: {{ join "," .Values.config.cors.origins | quote }}
        
        # Demo configuration
        - name: ENABLE_DEMO_USERS
          value: {{ .Values.config.demo.enabled | quote }}
        
        # Secrets
        {{- if .Values.secrets.jwtSecret }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "music21-mcp.secretName" . }}
              key: jwt-secret
        {{- end }}
        
        {{- if .Values.secrets.externalApiKey }}
        - name: EXTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "music21-mcp.secretName" . }}
              key: external-api-key
        {{- end }}
        
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          mountPath: /app/data
        {{- end }}
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
        
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
      
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "music21-mcp.fullname" . }}-data
      {{- end }}
      - name: logs-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}