apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: music21-mcp-server
  annotations:
    config.kubernetes.io/local-config: "true"

# Namespace for all resources
namespace: music21-mcp

# Resources to include
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- redis.yaml
- deployment.yaml
- hpa.yaml
- ingress.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: music21-mcp-server
  app.kubernetes.io/instance: production
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

# Images to update (for CI/CD)
images:
- name: music21-mcp-server
  newTag: latest

# ConfigMap generator for additional config
configMapGenerator:
- name: deployment-config
  literals:
  - DEPLOYMENT_TIMESTAMP=PLACEHOLDER_TIMESTAMP
  - DEPLOYMENT_VERSION=1.0.0
  - ENVIRONMENT=production

# Secret generator for runtime secrets
secretGenerator:
- name: runtime-secrets
  literals:
  - DATABASE_URL=PLACEHOLDER_DB_URL
  - REDIS_URL=redis://redis-service:6379/0

# Patches for different environments
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: music21-mcp-server
    namespace: music21-mcp
  spec:
    template:
      metadata:
        annotations:
          deployment/timestamp: PLACEHOLDER_TIMESTAMP

# Replicas for production
replicas:
- name: music21-mcp-server
  count: 3
- name: redis
  count: 1
- name: nginx
  count: 2

# Resource transformations
transformers:
- |-
  apiVersion: builtin
  kind: PrefixSuffixTransformer
  metadata:
    name: production-prefix
  prefix: prod-
  fieldSpecs:
  - path: metadata/name
    kind: ConfigMap
  - path: metadata/name
    kind: Secret