apiVersion: v1
kind: Namespace
metadata:
  name: music21-mcp
  labels:
    name: music21-mcp
    app.kubernetes.io/name: music21-mcp-server
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: music21-mcp-quota
  namespace: music21-mcp
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "3"
    pods: "10"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: music21-mcp-limits
  namespace: music21-mcp
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container