# Prometheus Alert Rules for Music21 MCP Server Enterprise
# Production-ready alerting for comprehensive monitoring

groups:
  - name: music21_mcp_critical_alerts
    interval: 30s
    rules:
      # Service Availability
      - alert: ServiceDown
        expr: up{job="music21-mcp"} == 0
        for: 1m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Music21 MCP Service is down"
          description: "The Music21 MCP server has been unreachable for more than 1 minute."
          runbook_url: "https://docs.music21-mcp.com/runbooks/service-down"

      # Error Rates
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(mcp_requests_total{status="error"}[5m]))
            /
            sum(rate(mcp_requests_total[5m]))
          ) > 0.05
        for: 5m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes (threshold: 5%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/high-error-rate"

      - alert: CriticalErrorRate
        expr: |
          (
            sum(rate(mcp_requests_total{status="error"}[5m]))
            /
            sum(rate(mcp_requests_total[5m]))
          ) > 0.20
        for: 2m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 2 minutes (threshold: 20%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-error-rate"

      # Response Time
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(mcp_request_duration_seconds_bucket[5m])) by (le)
          ) > 5
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "High response latency"
          description: "95th percentile latency is {{ $value }}s over the last 10 minutes (threshold: 5s)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/high-latency"

      - alert: CriticalLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(mcp_request_duration_seconds_bucket[5m])) by (le)
          ) > 30
        for: 5m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical response latency"
          description: "95th percentile latency is {{ $value }}s over the last 5 minutes (threshold: 30s)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-latency"

  - name: music21_mcp_resource_alerts
    interval: 60s
    rules:
      # Memory Usage
      - alert: HighMemoryUsage
        expr: music21_memory_usage_bytes{type="rss"} / 1024 / 1024 / 1024 > 6
        for: 5m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanize }}GB (threshold: 6GB)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/high-memory"

      - alert: CriticalMemoryUsage
        expr: music21_memory_usage_bytes{type="rss"} / 1024 / 1024 / 1024 > 12
        for: 2m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical memory usage"
          description: "Memory usage is {{ $value | humanize }}GB (threshold: 12GB)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-memory"

      # CPU Usage
      - alert: HighCPUUsage
        expr: music21_cpu_usage_percent > 80
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% over the last 10 minutes (threshold: 80%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/high-cpu"

      - alert: CriticalCPUUsage
        expr: music21_cpu_usage_percent > 95
        for: 5m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical CPU usage"
          description: "CPU usage is {{ $value }}% over the last 5 minutes (threshold: 95%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-cpu"

      # File Descriptors
      - alert: HighFileDescriptorUsage
        expr: music21_open_file_descriptors > 5000
        for: 5m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "High file descriptor usage"
          description: "Open file descriptors: {{ $value }} (threshold: 5000)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/file-descriptors"

  - name: music21_mcp_analysis_alerts
    interval: 60s
    rules:
      # Music Analysis Performance
      - alert: SlowMusicAnalysis
        expr: |
          histogram_quantile(0.95, 
            sum(rate(music21_analysis_duration_seconds_bucket[5m])) 
            by (le, analysis_type)
          ) > 30
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "Slow music analysis performance"
          description: "{{ $labels.analysis_type }} analysis is taking {{ $value }}s at 95th percentile (threshold: 30s)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/slow-analysis"

      - alert: CriticalAnalysisLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(music21_analysis_duration_seconds_bucket[5m])) 
            by (le, analysis_type)
          ) > 120
        for: 5m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical music analysis latency"
          description: "{{ $labels.analysis_type }} analysis is taking {{ $value }}s at 95th percentile (threshold: 120s)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-analysis-latency"

      # Analysis Queue
      - alert: HighAnalysisQueueDepth
        expr: music21_analysis_queue_size > 50
        for: 5m
        labels:
          severity: warning
          service: music21-mcp
        annotations:
          summary: "High analysis queue depth"
          description: "Analysis queue has {{ $value }} items (threshold: 50)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/queue-depth"

      - alert: CriticalAnalysisQueueDepth
        expr: music21_analysis_queue_size > 200
        for: 2m
        labels:
          severity: critical
          service: music21-mcp
        annotations:
          summary: "Critical analysis queue depth"
          description: "Analysis queue has {{ $value }} items (threshold: 200)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-queue-depth"

  - name: music21_mcp_security_alerts
    interval: 30s
    rules:
      # Authentication Issues
      - alert: HighAuthenticationFailureRate
        expr: |
          sum(rate(music21_auth_attempts_total{status="failure"}[5m])) 
          / 
          sum(rate(music21_auth_attempts_total[5m])) > 0.10
        for: 5m
        labels:
          severity: warning
          service: music21-mcp
          category: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value | humanizePercentage }} (threshold: 10%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/auth-failures"

      # Security Violations
      - alert: SecurityViolationDetected
        expr: increase(music21_security_violations_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: music21-mcp
          category: security
        annotations:
          summary: "Security violation detected"
          description: "{{ $value }} security violations of type {{ $labels.violation_type }} in the last 5 minutes"
          runbook_url: "https://docs.music21-mcp.com/runbooks/security-violations"

      - alert: CriticalSecurityViolation
        expr: increase(music21_security_violations_total{severity="critical"}[1m]) > 0
        for: 0m
        labels:
          severity: critical
          service: music21-mcp
          category: security
        annotations:
          summary: "Critical security violation detected"
          description: "Critical security violation of type {{ $labels.violation_type }} detected"
          runbook_url: "https://docs.music21-mcp.com/runbooks/critical-security"

      # Brute Force Detection
      - alert: PossibleBruteForceAttack
        expr: |
          sum(rate(music21_security_violations_total{
            violation_type="brute_force_attempt"
          }[15m])) > 5
        for: 1m
        labels:
          severity: critical
          service: music21-mcp
          category: security
        annotations:
          summary: "Possible brute force attack detected"
          description: "{{ $value }} brute force attempts detected in the last 15 minutes"
          runbook_url: "https://docs.music21-mcp.com/runbooks/brute-force"

      # Rate Limiting
      - alert: HighRateLimitHits
        expr: increase(music21_rate_limit_hits_total[5m]) > 50
        for: 2m
        labels:
          severity: warning
          service: music21-mcp
          category: security
        annotations:
          summary: "High rate of rate limit violations"
          description: "{{ $value }} rate limit violations in the last 5 minutes"
          runbook_url: "https://docs.music21-mcp.com/runbooks/rate-limits"

  - name: music21_mcp_resilience_alerts
    interval: 60s
    rules:
      # Circuit Breakers
      - alert: CircuitBreakerOpen
        expr: music21_circuit_breaker_state{state="open"} == 1
        for: 1m
        labels:
          severity: warning
          service: music21-mcp
          category: resilience
        annotations:
          summary: "Circuit breaker opened"
          description: "Circuit breaker {{ $labels.circuit_name }} is open"
          runbook_url: "https://docs.music21-mcp.com/runbooks/circuit-breaker"

      - alert: FrequentCircuitBreakerTrips
        expr: increase(music21_circuit_breaker_state_changes[1h]) > 5
        for: 5m
        labels:
          severity: warning
          service: music21-mcp
          category: resilience
        annotations:
          summary: "Frequent circuit breaker state changes"
          description: "Circuit breaker {{ $labels.circuit_name }} changed state {{ $value }} times in the last hour"
          runbook_url: "https://docs.music21-mcp.com/runbooks/circuit-breaker-instability"

      # Bulkhead Overload
      - alert: BulkheadHighUtilization
        expr: |
          music21_bulkhead_active_count / music21_bulkhead_max_concurrent > 0.90
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
          category: resilience
        annotations:
          summary: "High bulkhead utilization"
          description: "Bulkhead {{ $labels.bulkhead_name }} is {{ $value | humanizePercentage }} utilized"
          runbook_url: "https://docs.music21-mcp.com/runbooks/bulkhead-utilization"

      - alert: BulkheadQueueFull
        expr: music21_bulkhead_rejected_count > 0
        for: 1m
        labels:
          severity: critical
          service: music21-mcp
          category: resilience
        annotations:
          summary: "Bulkhead queue full"
          description: "Bulkhead {{ $labels.bulkhead_name }} is rejecting requests due to full queue"
          runbook_url: "https://docs.music21-mcp.com/runbooks/bulkhead-queue-full"

      # Retry Patterns
      - alert: HighRetryRate
        expr: |
          sum(rate(music21_retry_attempts_total[5m])) 
          / 
          sum(rate(music21_requests_total[5m])) > 0.20
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
          category: resilience
        annotations:
          summary: "High retry rate"
          description: "Retry rate is {{ $value | humanizePercentage }} (threshold: 20%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/high-retry-rate"

  - name: music21_mcp_business_alerts
    interval: 300s  # Check every 5 minutes
    rules:
      # SLA Compliance
      - alert: SLAViolation
        expr: music21_sla_compliance_percent < 99.5
        for: 15m
        labels:
          severity: warning
          service: music21-mcp
          category: business
        annotations:
          summary: "SLA compliance below threshold"
          description: "SLA compliance for {{ $labels.service }} is {{ $value }}% (threshold: 99.5%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/sla-violation"

      # Error Budget
      - alert: ErrorBudgetExhausted
        expr: music21_error_budget_remaining_percent < 10
        for: 5m
        labels:
          severity: critical
          service: music21-mcp
          category: business
        annotations:
          summary: "Error budget nearly exhausted"
          description: "Error budget for {{ $labels.service }} is {{ $value }}% remaining"
          runbook_url: "https://docs.music21-mcp.com/runbooks/error-budget"

      # Unusual Traffic Patterns
      - alert: UnusualTrafficPattern
        expr: |
          abs(
            sum(rate(mcp_requests_total[10m])) 
            - 
            sum(rate(mcp_requests_total[10m] offset 1w))
          ) / sum(rate(mcp_requests_total[10m] offset 1w)) > 0.50
        for: 30m
        labels:
          severity: info
          service: music21-mcp
          category: business
        annotations:
          summary: "Unusual traffic pattern detected"
          description: "Traffic is {{ $value | humanizePercentage }} different from the same time last week"
          runbook_url: "https://docs.music21-mcp.com/runbooks/traffic-patterns"

  - name: music21_mcp_data_alerts
    interval: 300s
    rules:
      # Data Quality
      - alert: HighFailedMusicProcessing
        expr: |
          sum(rate(music21_files_processed_total{status="error"}[1h])) 
          / 
          sum(rate(music21_files_processed_total[1h])) > 0.05
        for: 30m
        labels:
          severity: warning
          service: music21-mcp
          category: data_quality
        annotations:
          summary: "High music file processing failure rate"
          description: "{{ $value | humanizePercentage }} of music files failed to process in the last hour"
          runbook_url: "https://docs.music21-mcp.com/runbooks/processing-failures"

      # Storage Issues
      - alert: HighScoreStorageUsage
        expr: music21_corpus_size > 5000
        for: 10m
        labels:
          severity: warning
          service: music21-mcp
          category: storage
        annotations:
          summary: "High number of scores in memory"
          description: "{{ $value }} scores are currently stored in memory (threshold: 5000)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/memory-storage"

      # Cache Performance
      - alert: LowCacheHitRate
        expr: |
          sum(rate(music21_cache_hits_total[15m])) 
          / 
          (sum(rate(music21_cache_hits_total[15m])) + sum(rate(music21_cache_misses_total[15m]))) < 0.80
        for: 30m
        labels:
          severity: warning
          service: music21-mcp
          category: performance
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 80%)"
          runbook_url: "https://docs.music21-mcp.com/runbooks/cache-performance"